server:
  port: 8085

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=customerdb;encrypt=false;trustServerCertificate=true
    username: sa
    password: Admin12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs